<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "tasks".
 *
 * @property int $id
 * @property int $userId
 * @property string $title
 * @property string $content
 * @property int $createdAt
 * @property int $isSolved
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tasks';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userId', 'title', 'content'], 'required'],
            [['userId', 'createdAt', 'isSolved'], 'integer'],
            [['title', 'content'], 'string'],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class'                 =>  TimestampBehavior::class,
                'createdAtAttribute'    =>  'createdAt',
                'updatedAtAttribute'    =>  null
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userId' => 'User ID',
            'title' => 'Title',
            'content' => 'Content',
            'createdAt' => 'Created At',
            'isSolved' => 'Is Solved',
        ];
    }

    public function beforeValidate()
    {
        if ($this->userId === null) $this->userId = \Yii::$app->user->getIsGuest() ? 0 : \Yii::$app->user->id;

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
